### ISSUE TITLE
startArchive method throws an error when using ArchiveConfig::OUTPUT_MODE_INDIVIDUAL

### ISSUE THREAD

**Issue by shawndl** [Vonage/vonage-php-sdk-video#12]
Summary
The startArchive method throws an error when the output mode is set to ArchiveConfig::OUTPUT_MODE_INDIVIDUAL. The method works fine when the mode is set to ArchiveConfig::OUTPUT_MODE_COMPOSED.

Expected Behavior
When the output mode is set to ArchiveConfig::OUTPUT_MODE_INDIVIDUAL, the /v2/project/{applicationId}/archive endpoint should return a valid response, which can then be properly populated by the Archive class.

Current Behavior
The Archive class throws an error at line 136: 'Undefined array key "resolution"'.

Possible Solution
The request to /v2/project/{applicationId}/archive succeeds in both cases. However, when using ArchiveConfig::OUTPUT_MODE_INDIVIDUAL, the API throws an error if a resolution is specified. As a result, when the response is returned, a resolution value is included. A potential fix would be to add an if statement around line 136, which temporarily resolves the issue locally:

`$this->resolution = $data['resolution'] ?? '';`

You can find more information here:
https://developer.vonage.com/en/video/server-sdks/php#working-with-archives

Steps to Reproduce
1. Start an archive with the output mode set to ArchiveConfig::OUTPUT_MODE_INDIVIDUAL.
2. Observe the error thrown by the Archive class. 

Context
We are unable to successfully start an archive using individual mode without encountering this error.

Environment
Version used: 1.0.2
PHP version: 8.3.12
Operating System: macOS 15.0

**Comment by SecondeJK** [comment]
Fixed in 1.2.2, thanks for reporting!
