### ISSUE TITLE
Changed the code in README.md to the latest version

### ISSUE THREAD

**Issue by oooooooo** [Vonage/vonage-php-sdk-video#6]
Hi, I had to modify the code in README.md to get it to working.
In addition, I believe you also need the vonage/jwt package.
https://github.com/Vonage/vonage-php-sdk-video/compare/0.x...oooooooo:vonage-php-sdk-video:fix/readme?expand=1

Please also update the following documents. 📝
https://developer.vonage.com/en/video/server-sdks/php

**Comment by SecondeJK** [comment]
done, thanks for reporting
